#! /bin/sh

# Programs to start
feh --bg-fill ~/.config/bspwm/wall # set wallpaper
color salvation

dunst & # notifcations
#xrdb -remove # remove old xrdb settings
#xrdb $HOME/.config/Xresources # general xrdb resources
#xrdb -merge $HOME/.config/color/gruvbox-dark 
#poly-launch & # polybar launching script
#picom & # compositer
#conky -c $HOME/.config/conky/clock.conf


# Desktops & Displays
bspc monitor -d 1 2 3 4 5 6


# Borders & Gaps
bspc config border_width 2
bspc config window_gap 12
bspc config top_padding 42

bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Colors
## source the colors.
#. "${HOME}/.cache/wal/colors.sh"
#HIGHLIGHT=$(xrdb -query | awk '/cursorColor/ {print $2}')
#BACKGROUND=$(xrdb -query | awk '/background/ {print $2}')

#bspc config normal_border_color "$BACKGROUND"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$HIGHLIGHT"
#bspc config presel_feedback_color "$HIGHLIGHT"

# Misc
bspc config focus_follows_pointer true
bspc config split_ratio          0.52


# Program Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

